# GCC tsx+sequential build
# TMBUILD ?= tsxseq

# ======== Defines ========
CC       := gcc
CPPFLAGS += -DNDEBUG
CPPFLAGS += -I../lib -I../$(TMBUILD) -D_GNU_SOURCE
CFLAGS   += -Wall -Wextra
CFLAGS   += -O3 -mrtm

CFLAGS   += -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free

LD       := gcc
LDFLAGS  += -lpthread


TMLIBDIR ?= TMLIBDIR_IS_NOT_SET

include ../Makefile.common
